spring.application.name=contacerta

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/contacerta}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
#spring.jpa.show-sql=true

#spring.flyway.plugins.postgresql.ignore-future-versions=true

# server config
server.port=8080
server.servlet.context-path=/api/v1

app.security.jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION:}
app.security.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION:}
app.security.jwt.access-token-ttl=PT15M
app.security.session.refresh-token-ttl=P7D
app.security.password.bcrypt-strength=12

app.initial-admin.name=${INITIAL_ADMIN_NAME:}
app.initial-admin.email=${INITIAL_ADMIN_EMAIL:}
app.initial-admin.password=${INITIAL_ADMIN_PASSWORD:}
